name: pycompass
version: 1.1.0
summary: The Official CLI for Zype Programming Language.
description: |
  Compass is the official CLI for Zype Programming Language.
base: core18

parts:
  pycompass:
    plugin: python
    source: .

apps:
  pycompass:
    command: bin/pycompass
