name: pycompass
version: 1.0.0-linux-amd64
summary: The Official CLI for Zype Programming Language.
description: |
  Compass is the official CLI for Zype Programming Language.
base: core

parts:
  pycompass:
    plugin: python
    source: .

apps:
  pycompass:
    command: bin/pycompass
